@hostname=localhost
# @port=44300
@port=50830

POST https://{{hostname}}:{{port}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=is-nova-webapi-commands&client_secret=secret&scope=is-nova-webapi is-nova-webapi.command

###

POST https://{{hostname}}:{{port}}/connect/token
Authorization: Basic bXktYXBpLWNvbW1hbmRzOnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=is-nova-webapi is-nova-webapi.command

###

@api_hostname=localhost
@api_port=60889

GET https://{{api_hostname}}:{{api_port}}/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNGMkI0OEIzRDFBMTZGQTM5MzU4QjdGMzUyMUQ0RERDRTA0QUYwOTdSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IlB5dElzOUdoYjZPVFdMZnpVaDFOM09CSzhKYyJ9.eyJuYmYiOjE3Mjg5MDc0ODEsImV4cCI6MTcyODkxMTA4MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA4MzAiLCJhdWQiOiJpcy1ub3ZhLXdlYmFwaSIsImNsaWVudF9pZCI6ImlzLW5vdmEtd2ViYXBpLWNvbW1hbmRzIiwianRpIjoiRUExMzlEQkU5NDM5ODI0QkY4NTA0QUQ4QUE2REE5MjkiLCJpYXQiOjE3Mjg5MDc0ODEsInNjb3BlIjpbImlzLW5vdmEtd2ViYXBpIiwiaXMtbm92YS13ZWJhcGkuY29tbWFuZCJdfQ.DSZt-anHcP_eSWDHBj8SqWhVPGnwTDLiGqUH_L9CaMp28kiAL2rOdzxCCqAVI2LJ6lWPJka2UiMVbw91GPg5AGEIl-6PLL0ldNf90G0vp4GC0FfdsYtgpJcFpoDMNntKQJ-h79mQEDaeAWI7OKI_JOhPrSEI5kjWnjEdA04BwPyuGqH0jgjEufAm_30OvS8zi1I86nmPfcgV4fV-Dum_8yUh37u8QuyHvTk97ee4LNlZcU6GRJCylV7uY8VELMTuQ2r3mgu_p-fB9vHOlMDpK5ku9kWupOSwasScUuLBOj6901CzIBuBwID5Egg5IGeG4SdC-8hux1lkgwKDKn753A