@hostname=localhost
# @port=44300
@port=59640

POST https://{{hostname}}:{{port}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=is-nova-webapi-commands&client_secret=secret&scope=is-nova-webapi is-nova-webapi.command

###

POST https://{{hostname}}:{{port}}/connect/token
Authorization: Basic bXktYXBpLWNvbW1hbmRzOnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=is-nova-webapi is-nova-webapi.command

###

@api_hostname=localhost
@api_port=60889

GET https://{{api_hostname}}:{{api_port}}/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQwRUY5MzJFRTNDRUM4OUFCQzU1QkE4QkVEQUZBQzIxQTFENzg1MEVSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IlFPLVRMdVBPeUpxOFZicUw3YS1zSWFIWGhRNCJ9.eyJuYmYiOjE3MjkzMjkyNzksImV4cCI6MTcyOTMzMjg3OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTk2NDAiLCJhdWQiOiJpcy1ub3ZhLXdlYmFwaSIsImNsaWVudF9pZCI6ImlzLW5vdmEtd2ViYXBpLWNvbW1hbmRzIiwianRpIjoiMkI4OTk1RTI2RUNGNjY3MDdENDU5MEEzMkE5OEE1MUYiLCJpYXQiOjE3MjkzMjkyNzksInNjb3BlIjpbImlzLW5vdmEtd2ViYXBpIiwiaXMtbm92YS13ZWJhcGkuY29tbWFuZCJdfQ.QQr6lX4Bvez-3bYrXg0GB95FT3S5Bg_MMhw2S5-H2I3F0XJJq3yFPXT0UrCi5jbqhejJsYmj6vVDYVVvt1EvJGmtoUJ4HYTu_ba91aThImq0RH8q2QoARBfqTXvAEsF58zM3cxcd5kqkrEsuRKXrjlLE7Ikast2zuSrfHEai7AGMMBryiJ0ewPi5LsR4TFpbt7x1-ChU_UA73VNTPj08uCPSNGqqtES-d7P_JTGVj6MMisEVTXiGnzalmsa5swOL5EUj7hiA6u-rUltooY0k16G_lFBwsKGa3KZmcREJo7PfwY0uYUa3SU7XNkN6Y4Hmiblxj2DemeiMTgSuskInKA