POST https://localhost:44300/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=secrets-locker1&client_secret=secret1&scope=secrets-vault%20secrets-vault.locker1

###

GET https://localhost:44300/api/secretsvault?v=1.0&path=locker1/sec1/638543929896326114
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJFOTU3Q0I4RkM5NDIxM0JBNTZFQTI4MTlENjMzMkMzMTE0NjJFOTFSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IkxwVjh1UHlVSVR1bGJxS0JuV015d3hGR0xwRSJ9.eyJuYmYiOjE3MjE0NzQ1MDAsImV4cCI6MTcyMTQ3ODEwMCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDAiLCJhdWQiOiJzZWNyZXRzLXZhdWx0IiwiY2xpZW50X2lkIjoic2VjcmV0cy1sb2NrZXIxIiwianRpIjoiNjVEQTQ2MDE2NTVCRTlBOEY5MjVGNjFGREY4NDg4NDAiLCJpYXQiOjE3MjE0NzQ1MDAsInNjb3BlIjpbInNlY3JldHMtdmF1bHQiLCJzZWNyZXRzLXZhdWx0LmxvY2tlcjEiXX0.0n5RVsO8bwFNmFbg1__LhUs2Mv0T6ZC6gZu7EY2PsXlI8DKRgeqVW-thUuDo4XrkSHDsHu6gMCaK-UJt1JnncfnG4X0-m3WKi2Hp7ORuDRY6-4WXyz30PATzDmFJeFpvXTEyO5v5nyHhEEFpZZzexYafxe4lzLIBf7gOdY_Q1MYsm7DXa0Fq8oXB2QZXfnTh73yKEWmQkg0RZ5P61LqC96AYFa8uIFoAWWQhMNJrak-dzuDA5Im0wvT_RQT-cVGcc_L9Z2rpQ2HjJeRKxHzWvsTGKjIi9lxjyWX6JeSZV6napn2AvxQ8I5ygK6Ea79X0UjersWEb5uJFWwQfEdsdGg

###
