@hostname=localhost
# @port=44300
@port=62172

POST https://{{hostname}}:{{port}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=my-api-secrets&client_secret=secret&scope=secrets-vault secrets-vault.my-api-locker

###

GET https://{{hostname}}:{{port}}/api/secretsvault?v=1.0&path=my-api-locker/db-connectionstring
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRBNjQwODA4MzcwMUI1RURDM0EzMkJDRTg1OEEyMEJGMkQzQkRCM0ZSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IjJtUUlDRGNCdGUzRG95dk9oWW9ndnkwNzJ6OCJ9.eyJuYmYiOjE3MjQyNDczNTEsImV4cCI6MTcyNDI1MDk1MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDAiLCJhdWQiOiJzZWNyZXRzLXZhdWx0IiwiY2xpZW50X2lkIjoibXktYXBpLXNlY3JldHMiLCJqdGkiOiI4NEIyNTlBRTZGRDFDRDA0MTZENkYxRjJCMzAxMzhBNCIsImlhdCI6MTcyNDI0NzM1MSwic2NvcGUiOlsic2VjcmV0cy12YXVsdCIsInNlY3JldHMtdmF1bHQubXktYXBpLWxvY2tlciJdfQ.JQfdd8cUyKB0grcOdCi8YzwkAWyFNE3llcAZw-AYL6Us0vOciMtT8IJlr8UeK5hZtdUz3M9bli1Ty6iY0R_pCp-2EoAGzxgNeXp9kp4za16JD23l-rf2BCTfw32xfKibZklLAO1Kq5sWxCOLg5xIMcexk1ubTatQWViTHuyRyyS0L99ricVPPp6CJY1UOq-LZhS4CZcMEu8vAiKJRaAHacb8Xf4DeWuwKca1rsKHZILu1j3J7GC6caTCnUXAa6-d6NX-fEG6LYyfK8cGWYt8aJb_ngUM-9FGRN1IiaqUrTzo0teWLmXtDNkkI5Lka_x49HnEk99bqqo7jc72HoqCLA

###
