POST https://localhost:44300/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=signing-client&client_secret=secret1&scope=signing-api 

###

POST https://localhost:44300/api/signing
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3NkVCQjZENkQ1NkE0QUZFNjQ3MjFEMjI4RDIxQUZGRTYzQjE4NDFSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IloyNjdiVzFXcEtfbVJ5SFNLTklhXy1ZN0dFRSJ9.eyJuYmYiOjE3MTk0MDA2MjcsImV4cCI6MTcxOTQwNDIyNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDAiLCJhdWQiOiJzaWduaW5nLWFwaSIsImNsaWVudF9pZCI6InNpZ25pbmctY2xpZW50IiwianRpIjoiQUY0ODk2OUI5RUI4Nzg3Nzk1QTI2ODczM0Y3QzBCOTgiLCJpYXQiOjE3MTk0MDA2MjcsInNjb3BlIjpbInNpZ25pbmctYXBpIl19.QHh2oaYzp4pJXZCH7yRaOjdxaT-pkVk8SX0X-QZHdE_VuR5D7O_Bs3yd5unjNE0zNDeM3a2ifRjd4vS7-zRbcBPYAHKlOkahGvVbcQtc9o7IkNnXn6VRpXl4JmnlmJANXsVCvwPtL3XOMhquTb1ZcSfvHgNsgAWTzyx8A2qvF7kPHkSyvMuqdrDDSSVL0z8g4YOjr4q5WA_CafXwcI7plGW7EINRCV6OmxMVQjm7wPp0fr8M_798BWZZ7YIfXJSBw8lJJobxhLLMFNK6tfq3AnSdB71bBsZJqrA7Dp_akLATvF17R5bxJ5UvJCUAYZGjj9m4r2Z1HzVi4USfQaO5YQ
Content-Type: application/x-www-form-urlencoded

sub=1&name=user1&roles=

###